CREATE TABLE IF NOT EXISTS todo (
  id BIGSERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS tag (
  id BIGSERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS todo_tag (
  todo_id BIGINT NOT NULL REFERENCES todo (id) ON DELETE CASCADE,
  tag_id BIGINT NOT NULL REFERENCES tag (id) ON DELETE CASCADE,
  PRIMARY KEY (todo_id, tag_id)
);
